services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: kc_event_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./providers:/opt/keycloak/providers
    ports:
      - "8085:8080"
      -
    command:
      - start-dev
    networks:
      - keycloak_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
        - keycloak_network

# Persistent volumes configuration
volumes:
  postgres_data:
  pgadmin:
# Network configuration
networks:
  keycloak_network:
    driver: bridge