spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kc_event_test
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/keycloak-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    ssl:
      enabled: false
  threads:
    virtual:
      enabled: true


server:
  port: 8081
